### PR TITLE
alias can be written like labels

### PR DESCRIPTION
**Pull request by alemela**
I've used `label_or_description` in order to add an alias. It works like labels and descriptions so language code is needed.

I've used the API `wbsetaliases`.

### CODE REVIEW

**Comment by maxlath** [comment]
Thanks for starting working on it!

There is a difference between aliases and labels/descriptions that is that aliases accept several values per language: [`wbsetalias`](https://www.wikidata.org/w/api.php?action=help&modules=wbsetaliases) thus expects values to be passed with an action keyword: `add`, `remove`, or `set`, instead of `value` for labels and descriptions.

Request
url: `https://www.wikidata.org/w/api.php?action=wbsetaliases&format=json`
body: `id=Q4115189&language=fr&value=somevalue&assert=user&token=sometoken`

Response: `'Invalid list. (Parameters 'add' and 'remove' are not allowed to be set when parameter 'set' is provided)'`

**Comment by maxlath** [comment]
I added tests: the last one is currently failing

**Comment by alemela** [comment]
Thanks for test and suggestions!

I've written add and remove methods so now you can set more than one alias (using add). Set may be needless but now it behaves like API said.

**Comment by maxlath** [comment]
published as `v1.8.0`!

**Pull request merged**
