### PR TITLE
Add more time precision options

### PR DESCRIPTION
**Pull request by xrmx**
Work in progress PR to add more precision options for times. Need tests and glue to make callers of get_time_object aware of the new precision field. Backwards compatibility is preserved.
Working at this at Torino ODD18.

### CODE REVIEW

**Comment by xrmx** [comment]
Added tests and removed WIP.

**Comment by maxlath** [comment]
refactored to pass the same tests and cleaned a bit fb4abff

Todo:
- add more test for possible special cases: negative years
- document this new possibilities in the [How To](https://github.com/maxlath/wikidata-edit/blob/master/docs/how_to.md)

**Comment by xrmx** [comment]
I don't think I'll have time to hack more on it in the near future, feel free to tackle them. Thanks!

**Comment by maxlath** [comment]
re-merged as 35b2955 and published in `v2.1.0` \o/

**Comment by xrmx** [comment]
That was fast! Thanks @maxlath

**Comment by maxlath** [comment]
@xrmx you're very welcome, thanks for starting this PR! :D

**Pull request merged**
